class ProductPageLocators:
    product_card = "//a[@href='/product/Planshet-Digma-iDx10-8Gb/']"
    text_planshet = "//h1[@class='mb-lg-4']"
    add_to_card_button = "//button[contains(@class, 'rs-buy') and contains(@class, 'rs-to-cart')]"
    to_cart = "//a[text()='Перейти в корзину']"
    product_in_cart = "//a[@class='cart-checkout-item__title']"
    clear_cart_button = "//a[text()='Очистить']"
    card_button_from_home = "//span[text()='Корзина']"
    empty_cart = "//h2[text()='Корзина пуста']"
    add_to_favorites_button = "//span[text()='В избранное']"
    to_favorites_button = "//a[@href='/favorite/']"
    product_in_favorites = "//a[@class='item-card__title rs-to-product']"
    delete_from_favorites = "//a[@data-title='В избранное']"
    empty_favorites = "//div[text()='Нет товаров в избранном']"